export const activities = [
  {
    id: 1,
    verb: 'paid',
    subject: 'Caryl Raistrick',
    object: 'You',
    balance: 576,
    currency: 'USD',
  },
  {
    id: 2,
    verb: 'updated',
    subject: 'Eduardo Lamb',
    object: 'item 1 in group 1',
    balance: -381,
    currency: 'USD',
  },
  {
    id: 3,
    verb: 'paid',
    subject: 'Kevan Wenger',
    object: 'University Group',
    balance: 979,
    currency: 'USD',
  },
  {
    id: 4,
    verb: 'setting',
    subject: 'Simplify debt',
    object: 'turned off',
    balance: 223,
    currency: 'USD',
  },
  {
    id: 5,
    verb: 'updated',
    subject: 'Person 1',
    object: 'changed password',
    balance: 149,
    currency: 'USD',
  },
  {
    id: 6,
    verb: 'updated',
    subject: 'John Smith',
    object: 'his password',
    balance: -136,
    currency: 'USD',
  },
  {
    id: 7,
    verb: 'paid',
    subject: 'Maurita Sweynson',
    object: 'Group 1',
    balance: 880,
    currency: 'USD',
  },
];
