export const groups = [
  {
    id: '1Q10X57RN06',
    name: 'Dickinson, Prosacco and Bruen',
    balance: -81,
    currency: 'MXN',
    expense: [
      {
        id: 2,
        name: 'Michaella Tringham',
        balance: 526,
        currency: 'SEK',
      },
      {
        id: 2,
        name: "Maurine O'Sheerin",
        balance: -142,
        currency: 'GBP',
      },
    ],
  },
  {
    id: '8DQ2RN4PH51',
    name: 'Gislason, Krajcik and Zieme',
    balance: 161,
    currency: 'IDR',
    expense: [
      {
        id: 2,
        name: 'Enrichetta Koenraad',
        balance: -964,
        currency: 'IDR',
      },
    ],
  },
  {
    id: '3UA6EQ6UJ68',
    name: 'Wintheiser-Stoltenberg',
    balance: -114,
    currency: 'PKR',
    expense: [
      {
        id: 2,
        name: 'Jameson Inott',
        balance: -775,
        currency: 'UGX',
      },
      {
        id: 2,
        name: 'Sigfried Clousley',
        balance: -669,
        currency: 'IDR',
      },
    ],
  },
  {
    id: '3FJ7YY2GV46',
    name: 'Kihn-Wehner',
    balance: 155,
    currency: 'BYR',
    expense: [
      {
        id: 1,
        name: 'Bette Bingley',
        balance: -970,
        currency: 'RUB',
      },
    ],
  },
  {
    id: '3KP7WD2WG29',
    name: 'Beahan-Cormier',
    balance: -12,
    currency: 'GYD',
    expense: [],
  },
  {
    id: '8W43P51KH68',
    name: 'Hauck and Sons',
    balance: 65,
    currency: 'PLN',
    expense: [
      {
        id: 2,
        name: 'Annabella Korn',
        balance: -106,
        currency: 'EUR',
      },
      {
        id: 2,
        name: 'Darla Cronk',
        balance: 671,
        currency: 'RUB',
      },
    ],
  },
  {
    id: '8TP2JA6YR58',
    name: 'Ruecker LLC',
    balance: 152,
    currency: 'NGN',
    expense: [
      {
        id: 2,
        name: 'Dermot Rawne',
        balance: 140,
        currency: 'IDR',
      },
      {
        id: 1,
        name: 'Meggy Thornley',
        balance: -880,
        currency: 'PLN',
      },
    ],
  },
  {
    id: '2P13RY1AF03',
    name: 'Schroeder-Spencer',
    balance: -101,
    currency: 'EUR',
    expense: [
      {
        id: 2,
        name: 'Lauretta Van Driel',
        balance: -958,
        currency: 'IDR',
      },
      {
        id: 2,
        name: 'Egbert Heppner',
        balance: -659,
        currency: 'IDR',
      },
    ],
  },
  {
    id: '3JJ9UX7XN86',
    name: 'King-Klocko',
    balance: 72,
    currency: 'EUR',
    expense: [
      {
        id: 1,
        name: 'Esme Zannotti',
        balance: 519,
        currency: 'EUR',
      },
    ],
  },
  {
    id: '9J10NK4TF89',
    name: 'Blanda-Hilll',
    balance: -23,
    currency: 'XAF',
    expense: [],
  },
  {
    id: '3YA3AW3DW96',
    name: 'McGlynn, Blanda and Rowe',
    balance: -105,
    currency: 'PHP',
    expense: [
      {
        id: 2,
        name: 'Hermon Falkinder',
        balance: 377,
        currency: 'JPY',
      },
    ],
  },
  {
    id: '7JV6U82YH41',
    name: 'Altenwerth Inc',
    balance: 88,
    currency: 'EUR',
    expense: [
      {
        id: 1,
        name: 'Shani Brownscombe',
        balance: -725,
        currency: 'PLN',
      },
    ],
  },
  {
    id: '7HG0U54CF55',
    name: 'Beahan-Beahan',
    balance: 84,
    currency: 'EUR',
    expense: [],
  },
  {
    id: '5XM5T43EK02',
    name: 'Turner-Kilback',
    balance: 40,
    currency: 'EUR',
    expense: [
      {
        id: 1,
        name: 'Jecho Shipsey',
        balance: 682,
        currency: 'IDR',
      },
    ],
  },
  {
    id: '9CU4FA7WM77',
    name: 'Hauck, Lynch and Wisozk',
    balance: 55,
    currency: 'BRL',
    expense: [
      {
        id: 2,
        name: 'Evanne McLagain',
        balance: -738,
        currency: 'EUR',
      },
      {
        id: 2,
        name: 'Teodora Fettiplace',
        balance: 304,
        currency: 'PHP',
      },
    ],
  },
  {
    id: '4MH9JW0YW85',
    name: 'Fisher Group',
    balance: 82,
    currency: 'CNY',
    expense: [],
  },
  {
    id: '3GY4PD5WE11',
    name: 'Mann Inc',
    balance: 14,
    currency: 'AFN',
    expense: [
      {
        id: 2,
        name: 'Suzanna Bucknill',
        balance: 572,
        currency: 'CDF',
      },
    ],
  },
  {
    id: '5RM6R53AG72',
    name: 'McDermott-Bins',
    balance: 161,
    currency: 'GTQ',
    expense: [],
  },
  {
    id: '5R94YJ6GK95',
    name: 'Rodriguez, Kutch and Kunze',
    balance: 161,
    currency: 'RUB',
    expense: [],
  },
  {
    id: '6WX3MG6GW61',
    name: 'Konopelski, Towne and Ernser',
    balance: 12,
    currency: 'BRL',
    expense: [
      {
        id: 1,
        name: 'Garth Hitzke',
        balance: 288,
        currency: 'IDR',
      },
    ],
  },
  {
    id: '4N58P83WE35',
    name: 'Ortiz-Hammes',
    balance: 28,
    currency: 'ZWL',
    expense: [],
  },
  {
    id: '1KV7KJ6WH28',
    name: 'Cummings, Boehm and McGlynn',
    balance: 118,
    currency: 'CNY',
    expense: [],
  },
  {
    id: '9PF9W24ND74',
    name: 'Welch Inc',
    balance: 155,
    currency: 'EUR',
    expense: [
      {
        id: 2,
        name: 'Lilias Duke',
        balance: -454,
        currency: 'CNY',
      },
    ],
  },
  {
    id: '4A52JW6FX69',
    name: 'McLaughlin Inc',
    balance: 45,
    currency: 'EUR',
    expense: [],
  },
  {
    id: '5NH7MC3TA54',
    name: 'Murphy-Schulist',
    balance: 158,
    currency: 'THB',
    expense: [
      {
        id: 1,
        name: 'Carry Dulany',
        balance: 930,
        currency: 'PHP',
      },
      {
        id: 2,
        name: 'Catriona Gomar',
        balance: -816,
        currency: 'ARS',
      },
    ],
  },
  {
    id: '7VP4FG1XQ43',
    name: 'Weimann and Sons',
    balance: 119,
    currency: 'IDR',
    expense: [],
  },
  {
    id: '4C33GW6EQ89',
    name: 'Lang Inc',
    balance: 99,
    currency: 'EUR',
    expense: [
      {
        id: 2,
        name: 'Towny MacClinton',
        balance: 27,
        currency: 'RUB',
      },
      {
        id: 1,
        name: 'Lefty Sydenham',
        balance: -941,
        currency: 'PEN',
      },
    ],
  },
  {
    id: '2V10GR9YM14',
    name: 'Konopelski, Moore and Hayes',
    balance: 5,
    currency: 'RUB',
    expense: [],
  },
  {
    id: '6JD5Y50FW73',
    name: 'Shields and Sons',
    balance: 26,
    currency: 'ZAR',
    expense: [
      {
        id: 1,
        name: 'Renelle Edmand',
        balance: 922,
        currency: 'TND',
      },
      {
        id: 2,
        name: 'Eilis Tatham',
        balance: 419,
        currency: 'CNY',
      },
    ],
  },
  {
    id: '8GM4VD4DX06',
    name: 'Schowalter, Nader and Stoltenberg',
    balance: 175,
    currency: 'KZT',
    expense: [
      {
        id: 2,
        name: 'Herta Lownes',
        balance: 717,
        currency: 'MXN',
      },
    ],
  },
  {
    id: '2QM6R83WF63',
    name: 'Prosacco-Bernier',
    balance: 153,
    currency: 'PLN',
    expense: [
      {
        id: 2,
        name: 'Trace Wolfarth',
        balance: 993,
        currency: 'UAH',
      },
      {
        id: 2,
        name: 'Rooney Jakoviljevic',
        balance: 805,
        currency: 'BAM',
      },
    ],
  },
  {
    id: '1C48VK8TE84',
    name: 'Yundt-McGlynn',
    balance: 143,
    currency: 'KRW',
    expense: [
      {
        id: 2,
        name: 'Dede Braben',
        balance: 282,
        currency: 'COP',
      },
      {
        id: 1,
        name: 'Filia Whightman',
        balance: 155,
        currency: 'CNY',
      },
    ],
  },
  {
    id: '8V53KM4EC39',
    name: 'Schinner Group',
    balance: 15,
    currency: 'ETB',
    expense: [
      {
        id: 2,
        name: 'Mufinella Leys',
        balance: 20,
        currency: 'JPY',
      },
    ],
  },
  {
    id: '9P76DQ4QK26',
    name: 'Jerde, Bruen and Raynor',
    balance: 20,
    currency: 'IDR',
    expense: [
      {
        id: 2,
        name: 'Haroun Houchen',
        balance: -951,
        currency: 'CNY',
      },
      {
        id: 1,
        name: 'Torey Basilio',
        balance: 821,
        currency: 'PKR',
      },
    ],
  },
  {
    id: '1G21WX3DD70',
    name: 'Reichel Group',
    balance: 122,
    currency: 'BRL',
    expense: [
      {
        id: 2,
        name: 'Eal Yerrall',
        balance: -628,
        currency: 'IDR',
      },
    ],
  },
  {
    id: '4XD4C06UV83',
    name: 'Considine LLC',
    balance: 28,
    currency: 'CNY',
    expense: [
      {
        id: 2,
        name: 'Sheffield Hortop',
        balance: -962,
        currency: 'NGN',
      },
      {
        id: 1,
        name: 'Sharia Lebang',
        balance: 79,
        currency: 'BRL',
      },
    ],
  },
  {
    id: '4XU2CD4PR83',
    name: 'Sauer, Funk and Schultz',
    balance: 30,
    currency: 'PHP',
    expense: [],
  },
  {
    id: '6J95T93PP48',
    name: 'Lindgren-Herzog',
    balance: 125,
    currency: 'CNY',
    expense: [],
  },
  {
    id: '7CV0X87GC28',
    name: 'Bins Group',
    balance: 189,
    currency: 'CNY',
    expense: [
      {
        id: 2,
        name: 'Dugald Ongin',
        balance: 839,
        currency: 'CZK',
      },
      {
        id: 2,
        name: 'Doreen Barnfield',
        balance: -837,
        currency: 'EUR',
      },
    ],
  },
  {
    id: '9P71YQ8KQ13',
    name: 'Luettgen LLC',
    balance: 145,
    currency: 'CNY',
    expense: [
      {
        id: 1,
        name: 'Debora Luetchford',
        balance: 138,
        currency: 'RUB',
      },
    ],
  },
  {
    id: '8YX3NF3KF58',
    name: 'Lang-Reichert',
    balance: 15,
    currency: 'XAF',
    expense: [
      {
        id: 1,
        name: 'Thom Linne',
        balance: -909,
        currency: 'JMD',
      },
      {
        id: 2,
        name: 'Bren Chafer',
        balance: -241,
        currency: 'WST',
      },
    ],
  },
  {
    id: '7WK3N44VH59',
    name: 'Hirthe Group',
    balance: 120,
    currency: 'IDR',
    expense: [],
  },
  {
    id: '9VC6D29UF26',
    name: 'Mraz-Wiegand',
    balance: 8,
    currency: 'SEK',
    expense: [],
  },
  {
    id: '2NA8YJ3PM96',
    name: "O'Conner, Deckow and Bins",
    balance: 20,
    currency: 'RUB',
    expense: [
      {
        id: 2,
        name: 'Sylas Nibley',
        balance: 493,
        currency: 'CNY',
      },
    ],
  },
  {
    id: '3J92J85WC27',
    name: "Kohler-O'Connell",
    balance: 196,
    currency: 'CNY',
    expense: [
      {
        id: 2,
        name: 'Buiron Bassil',
        balance: 617,
        currency: 'EUR',
      },
      {
        id: 1,
        name: 'Ced Ramas',
        balance: -839,
        currency: 'SEK',
      },
    ],
  },
  {
    id: '8DY4XU1VD98',
    name: 'Morar and Sons',
    balance: 82,
    currency: 'BRL',
    expense: [
      {
        id: 1,
        name: 'Ottilie Smale',
        balance: 728,
        currency: 'PEN',
      },
      {
        id: 1,
        name: 'Peadar Lambrechts',
        balance: 355,
        currency: 'IDR',
      },
    ],
  },
  {
    id: '8GV8T49XA66',
    name: 'Schumm-Torphy',
    balance: 68,
    currency: 'EUR',
    expense: [],
  },
  {
    id: '1Y02P47PM71',
    name: 'Lindgren, Pfeffer and Emmerich',
    balance: 144,
    currency: 'EUR',
    expense: [
      {
        id: 2,
        name: 'Mala Klamp',
        balance: -715,
        currency: 'MNT',
      },
      {
        id: 1,
        name: 'Abra Yacobsohn',
        balance: -573,
        currency: 'CNY',
      },
    ],
  },
  {
    id: '9PT5F31PC50',
    name: 'Gusikowski-Leffler',
    balance: 99,
    currency: 'EUR',
    expense: [
      {
        id: 1,
        name: 'Madison Tullis',
        balance: 227,
        currency: 'BRL',
      },
    ],
  },
  {
    id: '6UP6XU8MT81',
    name: 'Waters and Sons',
    balance: 172,
    currency: 'AZN',
    expense: [
      {
        id: 2,
        name: 'Montague Cant',
        balance: 153,
        currency: 'HRK',
      },
    ],
  },
];
