# Generated by Django 5.1.4 on 2024-12-31 11:30

import django.db.models.deletion
import splinter.apps.media.models
import splinter.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', splinter.db.models.fields.UniqueUUIDField(editable=False)),
                ('removed_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('file', models.FileField(upload_to=splinter.apps.media.models.get_upload_path, validators=[splinter.apps.media.models.validate_file_size, splinter.apps.media.models.validate_image_extension])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(editable=False)),
                ('mime_type', models.CharField(editable=False, max_length=255)),
                ('object_id', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'media',
                'db_table': 'media',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='media_content_a5c40c_idx')],
            },
        ),
    ]
