volumes:
  postgresql:
  node_modules:

services:
  database:
    container_name: splinter-database
    hostname: splinter-database.local
    image: postgres:18
    environment:
      - "POSTGRES_USER=splinter"
      - "POSTGRES_PASSWORD=splinter"
      - "POSTGRES_DB=splinter"
    volumes:
      - postgresql:/var/lib/postgresql/
    ports:
      - "54321:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U splinter -d splinter" ]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    container_name: splinter-cache
    hostname: splinter-cache.local
    image: redis

  primary:
    container_name: splinter-primary
    hostname: splinter.local
    image: splinter
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - PUBLIC_DOMAIN=localhost:5173
      - CELERY_TASK_ALWAYS_EAGER=True
      - REDIS_HOST=splinter-cache.local
      - POSTGRES_HOSTNAME=splinter-database.local
      - POSTGRES_USERNAME=splinter
      - POSTGRES_PASSWORD=splinter
    command: >
      sh -c "
        splinter migrate &&
        splinter runserver 0.0.0.0:8000
      "
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./emails/:/tmp/splinter-emails/

  ui:
    container_name: splinter-ui
    hostname: splinter-ui
    image: node:24-alpine
    command: >
      sh -c "
        cd /app &&
        echo 'Installing Dependencies...' &&
        npm install &&
        echo 'Starting Development Server...' &&
        npm run dev
      "
    environment:
      - "NODE_ENV=development"
      - "OAPI_SCHEMA_URL:http://splinter.local:8000/api/schema"
      - "VITE_APP_BACKEND_URL=http://splinter.local:8000"
    volumes:
      - ./ui:/app
      - node_modules:/app/node_modules/
    ports:
      - "5173:5173"
