# Generated by Django 5.0.1 on 2024-02-11 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import splinter.apps.friend.models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='source',
            new_name='user_a',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='target',
            new_name='user_b',
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user_a',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user_a', 'user_b')},
        ),
    ]
