/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSetupRouteImport } from './routes/auth/setup'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgetRouteImport } from './routes/auth/forget'
import { Route as AuthAcceptRouteImport } from './routes/auth/accept'
import { Route as DashboardProfileMeRouteImport } from './routes/_dashboard/profile/me'

const DashboardGroupsLazyRouteImport = createFileRoute('/_dashboard/groups')()
const DashboardFriendsLazyRouteImport = createFileRoute('/_dashboard/friends')()
const DashboardActivityLazyRouteImport = createFileRoute(
  '/_dashboard/activity',
)()
const DashboardGroupsGroupLazyRouteImport = createFileRoute(
  '/_dashboard/groups/$group',
)()
const DashboardFriendsFriendLazyRouteImport = createFileRoute(
  '/_dashboard/friends/$friend',
)()
const DashboardActivityActivityLazyRouteImport = createFileRoute(
  '/_dashboard/activity/$activity',
)()
const DashboardGroupsGroupExpenseLazyRouteImport = createFileRoute(
  '/_dashboard/groups/$group/$expense',
)()
const DashboardFriendsFriendExpenseLazyRouteImport = createFileRoute(
  '/_dashboard/friends/$friend/$expense',
)()

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGroupsLazyRoute = DashboardGroupsLazyRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/groups.lazy').then((d) => d.Route),
)
const DashboardFriendsLazyRoute = DashboardFriendsLazyRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/friends.lazy').then((d) => d.Route),
)
const DashboardActivityLazyRoute = DashboardActivityLazyRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/activity.lazy').then((d) => d.Route),
)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/auth/setup',
  path: '/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgetRoute = AuthForgetRouteImport.update({
  id: '/auth/forget',
  path: '/auth/forget',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptRoute = AuthAcceptRouteImport.update({
  id: '/auth/accept',
  path: '/auth/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGroupsGroupLazyRoute =
  DashboardGroupsGroupLazyRouteImport.update({
    id: '/$group',
    path: '/$group',
    getParentRoute: () => DashboardGroupsLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/groups/$group.lazy').then((d) => d.Route),
  )
const DashboardFriendsFriendLazyRoute =
  DashboardFriendsFriendLazyRouteImport.update({
    id: '/$friend',
    path: '/$friend',
    getParentRoute: () => DashboardFriendsLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/friends/$friend.lazy').then((d) => d.Route),
  )
const DashboardActivityActivityLazyRoute =
  DashboardActivityActivityLazyRouteImport.update({
    id: '/$activity',
    path: '/$activity',
    getParentRoute: () => DashboardActivityLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/activity/$activity.lazy').then((d) => d.Route),
  )
const DashboardProfileMeRoute = DashboardProfileMeRouteImport.update({
  id: '/profile/me',
  path: '/profile/me',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsGroupExpenseLazyRoute =
  DashboardGroupsGroupExpenseLazyRouteImport.update({
    id: '/$expense',
    path: '/$expense',
    getParentRoute: () => DashboardGroupsGroupLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/groups/$group/$expense.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardFriendsFriendExpenseLazyRoute =
  DashboardFriendsFriendExpenseLazyRouteImport.update({
    id: '/$expense',
    path: '/$expense',
    getParentRoute: () => DashboardFriendsFriendLazyRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/friends/$friend/$expense.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/accept': typeof AuthAcceptRoute
  '/auth/forget': typeof AuthForgetRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/activity': typeof DashboardActivityLazyRouteWithChildren
  '/friends': typeof DashboardFriendsLazyRouteWithChildren
  '/groups': typeof DashboardGroupsLazyRouteWithChildren
  '/profile/me': typeof DashboardProfileMeRoute
  '/activity/$activity': typeof DashboardActivityActivityLazyRoute
  '/friends/$friend': typeof DashboardFriendsFriendLazyRouteWithChildren
  '/groups/$group': typeof DashboardGroupsGroupLazyRouteWithChildren
  '/friends/$friend/$expense': typeof DashboardFriendsFriendExpenseLazyRoute
  '/groups/$group/$expense': typeof DashboardGroupsGroupExpenseLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/accept': typeof AuthAcceptRoute
  '/auth/forget': typeof AuthForgetRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/activity': typeof DashboardActivityLazyRouteWithChildren
  '/friends': typeof DashboardFriendsLazyRouteWithChildren
  '/groups': typeof DashboardGroupsLazyRouteWithChildren
  '/profile/me': typeof DashboardProfileMeRoute
  '/activity/$activity': typeof DashboardActivityActivityLazyRoute
  '/friends/$friend': typeof DashboardFriendsFriendLazyRouteWithChildren
  '/groups/$group': typeof DashboardGroupsGroupLazyRouteWithChildren
  '/friends/$friend/$expense': typeof DashboardFriendsFriendExpenseLazyRoute
  '/groups/$group/$expense': typeof DashboardGroupsGroupExpenseLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/auth/accept': typeof AuthAcceptRoute
  '/auth/forget': typeof AuthForgetRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/setup': typeof AuthSetupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_dashboard/activity': typeof DashboardActivityLazyRouteWithChildren
  '/_dashboard/friends': typeof DashboardFriendsLazyRouteWithChildren
  '/_dashboard/groups': typeof DashboardGroupsLazyRouteWithChildren
  '/_dashboard/profile/me': typeof DashboardProfileMeRoute
  '/_dashboard/activity/$activity': typeof DashboardActivityActivityLazyRoute
  '/_dashboard/friends/$friend': typeof DashboardFriendsFriendLazyRouteWithChildren
  '/_dashboard/groups/$group': typeof DashboardGroupsGroupLazyRouteWithChildren
  '/_dashboard/friends/$friend/$expense': typeof DashboardFriendsFriendExpenseLazyRoute
  '/_dashboard/groups/$group/$expense': typeof DashboardGroupsGroupExpenseLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/accept'
    | '/auth/forget'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/setup'
    | '/auth/verify'
    | '/activity'
    | '/friends'
    | '/groups'
    | '/profile/me'
    | '/activity/$activity'
    | '/friends/$friend'
    | '/groups/$group'
    | '/friends/$friend/$expense'
    | '/groups/$group/$expense'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/accept'
    | '/auth/forget'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/setup'
    | '/auth/verify'
    | '/activity'
    | '/friends'
    | '/groups'
    | '/profile/me'
    | '/activity/$activity'
    | '/friends/$friend'
    | '/groups/$group'
    | '/friends/$friend/$expense'
    | '/groups/$group/$expense'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/auth/accept'
    | '/auth/forget'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/setup'
    | '/auth/verify'
    | '/_dashboard/activity'
    | '/_dashboard/friends'
    | '/_dashboard/groups'
    | '/_dashboard/profile/me'
    | '/_dashboard/activity/$activity'
    | '/_dashboard/friends/$friend'
    | '/_dashboard/groups/$group'
    | '/_dashboard/friends/$friend/$expense'
    | '/_dashboard/groups/$group/$expense'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthAcceptRoute: typeof AuthAcceptRoute
  AuthForgetRoute: typeof AuthForgetRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSetupRoute: typeof AuthSetupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/groups': {
      id: '/_dashboard/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof DashboardGroupsLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/friends': {
      id: '/_dashboard/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof DashboardFriendsLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/activity': {
      id: '/_dashboard/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof DashboardActivityLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/setup': {
      id: '/auth/setup'
      path: '/auth/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forget': {
      id: '/auth/forget'
      path: '/auth/forget'
      fullPath: '/auth/forget'
      preLoaderRoute: typeof AuthForgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept': {
      id: '/auth/accept'
      path: '/auth/accept'
      fullPath: '/auth/accept'
      preLoaderRoute: typeof AuthAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/groups/$group': {
      id: '/_dashboard/groups/$group'
      path: '/$group'
      fullPath: '/groups/$group'
      preLoaderRoute: typeof DashboardGroupsGroupLazyRouteImport
      parentRoute: typeof DashboardGroupsLazyRoute
    }
    '/_dashboard/friends/$friend': {
      id: '/_dashboard/friends/$friend'
      path: '/$friend'
      fullPath: '/friends/$friend'
      preLoaderRoute: typeof DashboardFriendsFriendLazyRouteImport
      parentRoute: typeof DashboardFriendsLazyRoute
    }
    '/_dashboard/activity/$activity': {
      id: '/_dashboard/activity/$activity'
      path: '/$activity'
      fullPath: '/activity/$activity'
      preLoaderRoute: typeof DashboardActivityActivityLazyRouteImport
      parentRoute: typeof DashboardActivityLazyRoute
    }
    '/_dashboard/profile/me': {
      id: '/_dashboard/profile/me'
      path: '/profile/me'
      fullPath: '/profile/me'
      preLoaderRoute: typeof DashboardProfileMeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/groups/$group/$expense': {
      id: '/_dashboard/groups/$group/$expense'
      path: '/$expense'
      fullPath: '/groups/$group/$expense'
      preLoaderRoute: typeof DashboardGroupsGroupExpenseLazyRouteImport
      parentRoute: typeof DashboardGroupsGroupLazyRoute
    }
    '/_dashboard/friends/$friend/$expense': {
      id: '/_dashboard/friends/$friend/$expense'
      path: '/$expense'
      fullPath: '/friends/$friend/$expense'
      preLoaderRoute: typeof DashboardFriendsFriendExpenseLazyRouteImport
      parentRoute: typeof DashboardFriendsFriendLazyRoute
    }
  }
}

interface DashboardActivityLazyRouteChildren {
  DashboardActivityActivityLazyRoute: typeof DashboardActivityActivityLazyRoute
}

const DashboardActivityLazyRouteChildren: DashboardActivityLazyRouteChildren = {
  DashboardActivityActivityLazyRoute: DashboardActivityActivityLazyRoute,
}

const DashboardActivityLazyRouteWithChildren =
  DashboardActivityLazyRoute._addFileChildren(
    DashboardActivityLazyRouteChildren,
  )

interface DashboardFriendsFriendLazyRouteChildren {
  DashboardFriendsFriendExpenseLazyRoute: typeof DashboardFriendsFriendExpenseLazyRoute
}

const DashboardFriendsFriendLazyRouteChildren: DashboardFriendsFriendLazyRouteChildren =
  {
    DashboardFriendsFriendExpenseLazyRoute:
      DashboardFriendsFriendExpenseLazyRoute,
  }

const DashboardFriendsFriendLazyRouteWithChildren =
  DashboardFriendsFriendLazyRoute._addFileChildren(
    DashboardFriendsFriendLazyRouteChildren,
  )

interface DashboardFriendsLazyRouteChildren {
  DashboardFriendsFriendLazyRoute: typeof DashboardFriendsFriendLazyRouteWithChildren
}

const DashboardFriendsLazyRouteChildren: DashboardFriendsLazyRouteChildren = {
  DashboardFriendsFriendLazyRoute: DashboardFriendsFriendLazyRouteWithChildren,
}

const DashboardFriendsLazyRouteWithChildren =
  DashboardFriendsLazyRoute._addFileChildren(DashboardFriendsLazyRouteChildren)

interface DashboardGroupsGroupLazyRouteChildren {
  DashboardGroupsGroupExpenseLazyRoute: typeof DashboardGroupsGroupExpenseLazyRoute
}

const DashboardGroupsGroupLazyRouteChildren: DashboardGroupsGroupLazyRouteChildren =
  {
    DashboardGroupsGroupExpenseLazyRoute: DashboardGroupsGroupExpenseLazyRoute,
  }

const DashboardGroupsGroupLazyRouteWithChildren =
  DashboardGroupsGroupLazyRoute._addFileChildren(
    DashboardGroupsGroupLazyRouteChildren,
  )

interface DashboardGroupsLazyRouteChildren {
  DashboardGroupsGroupLazyRoute: typeof DashboardGroupsGroupLazyRouteWithChildren
}

const DashboardGroupsLazyRouteChildren: DashboardGroupsLazyRouteChildren = {
  DashboardGroupsGroupLazyRoute: DashboardGroupsGroupLazyRouteWithChildren,
}

const DashboardGroupsLazyRouteWithChildren =
  DashboardGroupsLazyRoute._addFileChildren(DashboardGroupsLazyRouteChildren)

interface DashboardRouteChildren {
  DashboardActivityLazyRoute: typeof DashboardActivityLazyRouteWithChildren
  DashboardFriendsLazyRoute: typeof DashboardFriendsLazyRouteWithChildren
  DashboardGroupsLazyRoute: typeof DashboardGroupsLazyRouteWithChildren
  DashboardProfileMeRoute: typeof DashboardProfileMeRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityLazyRoute: DashboardActivityLazyRouteWithChildren,
  DashboardFriendsLazyRoute: DashboardFriendsLazyRouteWithChildren,
  DashboardGroupsLazyRoute: DashboardGroupsLazyRouteWithChildren,
  DashboardProfileMeRoute: DashboardProfileMeRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthAcceptRoute: AuthAcceptRoute,
  AuthForgetRoute: AuthForgetRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSetupRoute: AuthSetupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
