# Generated by Django 5.2.14 on 2026-05-30 14:45

import django.db.models.deletion
from django.db import migrations, models

import splinter.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageParse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', splinter.db.models.fields.UniqueUUIDField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment')], max_length=16)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('processing', 'Processing'),
                            ('done', 'Done'),
                            ('failed', 'Failed'),
                        ],
                        default='pending',
                        max_length=16,
                    ),
                ),
                ('provider', models.CharField(max_length=128)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                (
                    'media_file',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='parses', to='media.mediafile'
                    ),
                ),
            ],
            options={
                'db_table': 'image_parses',
                'ordering': ('-created_at',),
            },
        ),
    ]
