# Generated by Django 5.0.6 on 2026-04-23 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('currency', '0003_more_meta_and_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityaudience',
            name='currency',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='currency.currency',
            ),
        ),
        migrations.AddField(
            model_name='activityaudience',
            name='outstanding_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
