# Generated by Django 5.0.1 on 2024-03-18 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'ordering': ('created_at', )},
        ),
    ]
