# Generated by Django 5.0.1 on 2024-02-11 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        ('friend', '0002_rename_friendship_cols'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'expense',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to='expense.expense'
                    )
                ),
                (
                    'friendship',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='+', to='friend.friendship'
                    )
                ),
            ],
            options={
                'db_table': 'expense_parties',
                'unique_together': {('expense', 'friendship')},
            },
        ),
    ]
