# Generated by Django 5.2.15 on 2026-09-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_expense_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstandingbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
