export const Paths = {
  AUTHENTICATE_USER: '/api/user/authenticate',
  BULK_GROUP_MEMBERSHIP: '/api/group/members',
  CHALLENGE_MFA_DEVICE: '/api/mfa/challenge/{device}',
  CHANGE_PASSWORD: '/api/user/password',
  CONFIRM_MFA_DEVICE: '/api/mfa/confirm/{device}',
  CURRENCY_LIST: '/api/currency/all',
  EMAIL_VERIFICATION: '/api/user/verify-email',
  ENABLE_MFA_DEVICE: '/api/mfa/enable/{device}',
  FORGET_PASSWORD: '/api/user/forget',
  FRIEND_LIST: '/api/friend/all',
  GROUP: '/api/group/{group}',
  GROUP_MEMBERSHIP: '/api/group/{group}/members/{member}',
  GROUP_LIST: '/api/group/all',
  INVITE_FRIEND: '/api/friend/invite',
  LOGOUT: '/api/user/logout',
  MFA_DEVICE: '/api/mfa/device/{device}:{id}',
  MFA_DEVICE_LIST: '/api/mfa/devices',
  MFA_STATIC_CODE_LIST: '/api/mfa/static',
  RESET_PASSWORD: '/api/user/reset',
  USER_PROFILE: '/api/user/profile',
  VERIFY_MFA_DEVICE: '/api/mfa/verify/{device}',
} as const;
