export const Paths = {
  AUTHENTICATE_USER: '/api/user/authenticate',
  CHALLENGE_MFA_DEVICE: '/api/mfa/challenge/{device}',
  CHANGE_PASSWORD: '/api/user/password',
  CONFIRM_MFA_DEVICE: '/api/mfa/confirm/{device}',
  CREATE_GROUP: '/api/group/all',
  CREATE_GROUP_MEMBERSHIP: '/api/group/members',
  DESTROY_GROUP_MEMBERSHIP: '/api/group/{group}/members/{member}',
  DESTROY_MFA_DEVICE: '/api/mfa/device/{device}:{id}',
  EMAIL_VERIFICATION: '/api/user/verify-email',
  ENABLE_MFA_DEVICE: '/api/mfa/enable/{device}',
  FORGET_PASSWORD: '/api/user/forget',
  INVITE_FIEND: '/api/friend/invite',
  LIST_CURRENCY: '/api/currency/all',
  LIST_FIEND: '/api/friend/all',
  LIST_MFA_DEVICE: '/api/mfa/devices',
  LIST_MFA_STATIC_CODE: '/api/mfa/static',
  LOGOUT: '/api/user/logout',
  PARTIAL_UPDATE_GROUP: '/api/group/{group}',
  PARTIAL_UPDATE_USER_PROFILE: '/api/user/profile',
  RESET_PASSWORD: '/api/user/reset',
  VERIFY_MFA_DEVICE: '/api/mfa/verify/{device}',
} as const;
