export const Paths = {
  AUTHENTICATE_USER: '/api/user/authenticate',
  BULK_CREATE_GROUP_MEMBERSHIP: '/api/group/members',
  CHALLENGE_MFA_DEVICE: '/api/mfa/challenge/{device_type}',
  CHANGE_PASSWORD: '/api/user/password',
  CONFIRM_MFA_DEVICE: '/api/mfa/confirm/{device_type}',
  CURRENCY_LIST: '/api/currency/all',
  ENABLE_MFA_DEVICE: '/api/mfa/enable/{device_type}',
  FORGET_PASSWORD: '/api/user/forget',
  FRIEND_LIST: '/api/friend/all',
  GROUP_DETAIL: '/api/group/{group_uid}',
  GROUP_LIST: '/api/group/all',
  GROUP_MEMBERSHIP_DETAIL: '/api/group/{group_uid}/members/{member_uid}',
  INVITE_FRIEND: '/api/friend/invite',
  LOGOUT: '/api/user/logout',
  MFA_DEVICE_DETAIL: '/api/mfa/device/{device_type}:{id}',
  MFA_DEVICE_LIST: '/api/mfa/devices',
  MFA_STATIC_CODE_LIST: '/api/mfa/static',
  PROFILE: '/api/user/profile',
  RESET_PASSWORD: '/api/user/reset',
  VERIFY_EMAIL: '/api/user/verify-email',
  VERIFY_MFA_DEVICE: '/api/mfa/verify/{device_type}',
} as const;
